server:
  port: 8081

# JPA
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: root
    password: ${SPRING_DATASOURCE_PASSWORD}

  web:
    cors:
      allowed-origins: "http://localhost:8080"
      allowed-methods: "GET,POST, PUT, DELETE"



  thymeleaf:
    prefix: classpath:/static/
    suffix: .html

  springdoc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html
      display-request-duration: true
      operations-sorter: alpha

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: false
    hibernate:
      format_sql: true
      ddl-auto: update # 테이블 자동 생성
    properties:
      hibernate:
        format_sql: true


logging:
  level:
    org.hibernate.SQL: ERROR
    org.hibernate.type.descriptor.sql.BasicBinder: ERROR
    com.example.vegetabledragon: DEBUG

flask:
  api:
    url: "https://72a4-34-82-115-4.ngrok-free.app/predict"

    # 절대 url 에서 s를 빼먹어선 안돼.